name: GitHub Repository Crawler

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_crawler
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Crawl repositories
      run: python main.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/github_crawler

    - name: Export data
      run: |
        python -c "
        import asyncio, asyncpg, json, csv, os
        async def export():
            conn = await asyncpg.connect(os.environ['DATABASE_URL'])
            rows = await conn.fetch('SELECT github_id, name_with_owner, star_count FROM repositories ORDER BY star_count DESC')
            await conn.close()
            
            data = [{'github_id': r[0], 'name_with_owner': r[1], 'star_count': r[2]} for r in rows]
            
            with open('repositories.json', 'w') as f:
                json.dump(data, f, indent=2)
            
            with open('repositories.csv', 'w', newline='') as f:
                writer = csv.DictWriter(f, fieldnames=['github_id', 'name_with_owner', 'star_count'])
                writer.writeheader()
                writer.writerows(data)
            
            print(f'Exported {len(data)} repositories')

        asyncio.run(export())
        "
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/github_crawler

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: github-repositories
        path: |
          repositories.json
          repositories.csv
